### ISSUE TITLE
Hey. compile the program please

### ISSUE THREAD

**Issue by C-A-T9LIFE** [mathijsco/StackSharing#4]
Hey. compile the program please

**Comment by StefH** [comment]
Here is your **cake**, you can build it yourself ;-)


![c](https://user-images.githubusercontent.com/249938/30048119-fb3b5c1e-9214-11e7-82d1-f17235a9f88b.jpg)

**Comment by C-A-T9LIFE** [comment]
)))
I'm not a programmer

**Comment by StefH** [comment]
See https://github.com/StefH/StackSharing/releases/tag/2017-09-05 and download "StackSharing_2017-09-05.zip"

**Comment by C-A-T9LIFE** [comment]
Thank you! :)

**Comment by mathijsco** [comment]
Lol, missed this conversation. Luckily StefH is here to save the day :smile:
